# Generated by Django 5.1.6 on 2025-06-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='stocks.company')),
            ],
            options={
                'ordering': ['symbol', '-date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='stocks_hist_symbol_bfe1be_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
